plot.loglog.color <- function(df, xdata, sightangle, xtext, ytext, ymax, both){
  
  ### Takes data from limpet_analysis.R and data.frame of summary stats
  ### (mean and standard deviation) generated by av.and.std.R and 
  ### visualizes the raw results on log-log plots, in color.  df is
  ### the data.frame from av.and.std.R containing averages and standard
  ### deviations across replicates.  xdata is a column vector that 
  ### is plotted on the x-axis.  xtext and ytext are strings that will
  ### go in the x and y labels of the plots.  ymax is an integer 
  ### indicating the highest possible value on the y-axis.  sightangle
  ### is an integer, either 60 or 360, indicating which rows of df
  ### should be graphed.  both can be either True or False, and indicates
  ### whether both sightangle=60 and sightangle=360 should be plotted
  ### on the same graph.
  
  if (sightangle == 60 && both==FALSE) {
    
    par(mfrow=c(2,3))
    plot(log(df$averages1_0_60) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 0', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_0_60) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_0_60) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_0_60) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_0_60) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_1_60) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 1', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_1_60) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_1_60) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_1_60) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_1_60) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_2_60) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 2', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_2_60) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_2_60) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_2_60) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_2_60) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_5_60) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 5', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_5_60) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_5_60) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_5_60) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_5_60) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_10_60) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 10', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_10_60) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_10_60) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_10_60) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_10_60) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_20_60) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 20', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_20_60) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_20_60) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_20_60) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_20_60) ~ log(unique(xdata)), col='red', pch = 19)
    
  }
  
  if (sightangle == 360 && both==FALSE) {
    
    par(mfrow=c(2,3))
    plot(log(df$averages1_0_360) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 0', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_0_360) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_0_360) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_0_360) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_0_360) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_1_360) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 1', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_1_360) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_1_360) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_1_360) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_1_360) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_2_360) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 2', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_2_360) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_2_360) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_2_360) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_2_360) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_5_360) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 5', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_5_360) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_5_360) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_5_360) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_5_360) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_10_360) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 10', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_10_360) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_10_360) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_10_360) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_10_360) ~ log(unique(xdata)), col='red', pch = 19)
    
    plot(log(df$averages1_20_360) ~ log(unique(xdata)), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 20', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_20_360) ~ log(unique(xdata)), col='blue', pch = 19)
    points(log(df$averages2_20_360) ~ log(unique(xdata)), col='green', pch = 19)
    points(log(df$averages2.5_20_360) ~ log(unique(xdata)), col='yellow', pch = 19)
    points(log(df$averages3_20_360) ~ log(unique(xdata)), col='red', pch = 19)
    
  }
  
  if (both == TRUE) {
    
    par(mfrow=c(2,3))
    plot(log(df$averages1_0_60) ~ log(unique(xdata)), col='#08519c', xlab = xtext, 
         ylab = ytext, main = 'Sight = 0', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_0_60) ~ log(unique(xdata)), col='#3182bd', pch = 19)
    points(log(df$averages2_0_60) ~ log(unique(xdata)), col='#6baed6', pch = 19)
    points(log(df$averages2.5_0_60) ~ log(unique(xdata)), col='#9ecae1', pch = 19)
    points(log(df$averages3_0_60) ~ log(unique(xdata)), col='#c6dbef', pch = 19)
    points(log(df$averages1_0_360) ~ log(unique(xdata)), col='#a63603', pch = 19)
    points(log(df$averages1.5_0_360) ~ log(unique(xdata)), col='#e6550d', pch = 19)
    points(log(df$averages2_0_360) ~ log(unique(xdata)), col='#fd8d3c', pch = 19)
    points(log(df$averages2.5_0_360) ~ log(unique(xdata)), col='#fdae6b', pch = 19)
    points(log(df$averages3_0_360) ~ log(unique(xdata)), col='#fdd0a2', pch = 19)
    
    plot(log(df$averages1_1_60) ~ log(unique(xdata)), col='#08519c', xlab = xtext, 
         ylab = ytext, main = 'Sight = 1', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_1_60) ~ log(unique(xdata)), col='#3182bd', pch = 19)
    points(log(df$averages2_1_60) ~ log(unique(xdata)), col='#6baed6', pch = 19)
    points(log(df$averages2.5_1_60) ~ log(unique(xdata)), col='#9ecae1', pch = 19)
    points(log(df$averages3_1_60) ~ log(unique(xdata)), col='#c6dbef', pch = 19)
    points(log(df$averages1_1_360) ~ log(unique(xdata)), col='#a63603', pch = 19)
    points(log(df$averages1.5_1_360) ~ log(unique(xdata)), col='#e6550d', pch = 19)
    points(log(df$averages2_1_360) ~ log(unique(xdata)), col='#fd8d3c', pch = 19)
    points(log(df$averages2.5_1_360) ~ log(unique(xdata)), col='#fdae6b', pch = 19)
    points(log(df$averages3_1_360) ~ log(unique(xdata)), col='#fdd0a2', pch = 19)
    
    plot(log(df$averages1_2_60) ~ log(unique(xdata)), col='#08519c', xlab = xtext, 
         ylab = ytext, main = 'Sight = 2', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_2_60) ~ log(unique(xdata)), col='#3182bd', pch = 19)
    points(log(df$averages2_2_60) ~ log(unique(xdata)), col='#6baed6', pch = 19)
    points(log(df$averages2.5_2_60) ~ log(unique(xdata)), col='#9ecae1', pch = 19)
    points(log(df$averages3_2_60) ~ log(unique(xdata)), col='#c6dbef', pch = 19)
    points(log(df$averages1_2_360) ~ log(unique(xdata)), col='#a63603', pch = 19)
    points(log(df$averages1.5_2_360) ~ log(unique(xdata)), col='#e6550d', pch = 19)
    points(log(df$averages2_2_360) ~ log(unique(xdata)), col='#fd8d3c', pch = 19)
    points(log(df$averages2.5_2_360) ~ log(unique(xdata)), col='#fdae6b', pch = 19)
    points(log(df$averages3_2_360) ~ log(unique(xdata)), col='#fdd0a2', pch = 19)
    
    plot(log(df$averages1_5_60) ~ log(unique(xdata)), col='#08519c', xlab = xtext, 
         ylab = ytext, main = 'Sight = 5', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_5_60) ~ log(unique(xdata)), col='#3182bd', pch = 19)
    points(log(df$averages2_5_60) ~ log(unique(xdata)), col='#6baed6', pch = 19)
    points(log(df$averages2.5_5_60) ~ log(unique(xdata)), col='#9ecae1', pch = 19)
    points(log(df$averages3_5_60) ~ log(unique(xdata)), col='#c6dbef', pch = 19)
    points(log(df$averages1_5_360) ~ log(unique(xdata)), col='#a63603', pch = 19)
    points(log(df$averages1.5_5_360) ~ log(unique(xdata)), col='#e6550d', pch = 19)
    points(log(df$averages2_5_360) ~ log(unique(xdata)), col='#fd8d3c', pch = 19)
    points(log(df$averages2.5_5_360) ~ log(unique(xdata)), col='#fdae6b', pch = 19)
    points(log(df$averages3_5_360) ~ log(unique(xdata)), col='#fdd0a2', pch = 19)
    
    plot(log(df$averages1_10_60) ~ log(unique(xdata)), col='#08519c', xlab = xtext, 
         ylab = ytext, main = 'Sight = 10', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_10_60) ~ log(unique(xdata)), col='#3182bd', pch = 19)
    points(log(df$averages2_10_60) ~ log(unique(xdata)), col='#6baed6', pch = 19)
    points(log(df$averages2.5_10_60) ~ log(unique(xdata)), col='#9ecae1', pch = 19)
    points(log(df$averages3_10_60) ~ log(unique(xdata)), col='#c6dbef', pch = 19)
    points(log(df$averages1_10_360) ~ log(unique(xdata)), col='#a63603', pch = 19)
    points(log(df$averages1.5_10_360) ~ log(unique(xdata)), col='#e6550d', pch = 19)
    points(log(df$averages2_10_360) ~ log(unique(xdata)), col='#fd8d3c', pch = 19)
    points(log(df$averages2.5_10_360) ~ log(unique(xdata)), col='#fdae6b', pch = 19)
    points(log(df$averages3_10_360) ~ log(unique(xdata)), col='#fdd0a2', pch = 19)
    
    plot(log(df$averages1_20_60) ~ log(unique(xdata)), col='#08519c', xlab = xtext, 
         ylab = ytext, main = 'Sight = 20', ylim = c(0,ymax), pch = 19)
    points(log(df$averages1.5_20_60) ~ log(unique(xdata)), col='#3182bd', pch = 19)
    points(log(df$averages2_20_60) ~ log(unique(xdata)), col='#6baed6', pch = 19)
    points(log(df$averages2.5_20_60) ~ log(unique(xdata)), col='#9ecae1', pch = 19)
    points(log(df$averages3_20_60) ~ log(unique(xdata)), col='#c6dbef', pch = 19)
    points(log(df$averages1_20_360) ~ log(unique(xdata)), col='#a63603', pch = 19)
    points(log(df$averages1.5_20_360) ~ log(unique(xdata)), col='#e6550d', pch = 19)
    points(log(df$averages2_20_360) ~ log(unique(xdata)), col='#fd8d3c', pch = 19)
    points(log(df$averages2.5_20_360) ~ log(unique(xdata)), col='#fdae6b', pch = 19)
    points(log(df$averages3_20_360) ~ log(unique(xdata)), col='#fdd0a2', pch = 19)
    
  }
  
}