plot.bw <- function(df, xdata, sightangle, xtext, ytext, ymax, both){
  
  ### Takes data from limpet_analysis.R and data.frame of summary stats
  ### (mean and standard deviation) generated by av.and.std.R and 
  ### visualizes the raw results, in black and white.  df is
  ### the data.frame from av.and.std.R containing averages and standard
  ### deviations across replicates.  xdata is a column vector that 
  ### is plotted on the x-axis.  xtext and ytext are strings that will
  ### go in the x and y labels of the plots.  ymax is an integer 
  ### indicating the highest possible value on the y-axis.  sightangle
  ### is an integer, either 60 or 360, indicating which rows of df
  ### should be graphed.  both can be either True or False, and indicates
  ### whether both sightangle=60 and sightangle=360 should be plotted
  ### on the same graph.
  
  if (sightangle == 60 && both==FALSE) {
    
    par(mfrow=c(2,3))
    plot(df$averages1_0_60 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 0', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_0_60 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_0_60 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_0_60 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_0_60 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_1_60 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 1', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_1_60 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_1_60 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_1_60 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_1_60 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_2_60 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 2', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_2_60 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_2_60 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_2_60 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_2_60 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_5_60 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 5', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_5_60 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_5_60 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_5_60 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_5_60 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_10_60 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 10', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_10_60 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_10_60 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_10_60 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_10_60 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_20_60 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 20', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_20_60 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_20_60 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_20_60 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_20_60 ~ unique(xdata), col='red', pch = 19)
    
  }
  
  if (sightangle == 360 && both==FALSE) {
    
    par(mfrow=c(2,3))
    plot(df$averages1_0_360 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 0', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_0_360 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_0_360 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_0_360 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_0_360 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_1_360 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 1', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_1_360 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_1_360 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_1_360 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_1_360 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_2_360 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 2', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_2_360 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_2_360 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_2_360 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_2_360 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_5_360 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 5', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_5_360 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_5_360 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_5_360 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_5_360 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_10_360 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 10', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_10_360 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_10_360 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_10_360 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_10_360 ~ unique(xdata), col='red', pch = 19)
    
    plot(df$averages1_20_360 ~ unique(xdata), col='black', xlab = xtext, 
         ylab = ytext, main = 'Sight = 20', ylim = c(0,ymax), pch = 19)
    points(df$averages1.5_20_360 ~ unique(xdata), col='blue', pch = 19)
    points(df$averages2_20_360 ~ unique(xdata), col='green', pch = 19)
    points(df$averages2.5_20_360 ~ unique(xdata), col='yellow', pch = 19)
    points(df$averages3_20_360 ~ unique(xdata), col='red', pch = 19)
    
  }
  
  if (both == TRUE) {
    
    par(mfrow=c(2,3), mar=c(4,4,3,1)+0.1)
    plot(df$averages1_0_60 ~ unique(xdata), col='#f7f7f7', xlab = xtext, 
         ylab = ytext, main = 'Sight = 0', ylim = c(0,ymax), pch = 19, cex = 0.5)
    points(df$averages1.5_0_60 ~ unique(xdata), col='#cccccc', pch = 19, cex = 0.5)
    points(df$averages2_0_60 ~ unique(xdata), col='#969696', pch = 19, cex = 0.5)
    points(df$averages2.5_0_60 ~ unique(xdata), col='#636363', pch = 19, cex = 0.5)
    points(df$averages3_0_60 ~ unique(xdata), col='#252525', pch = 19, cex = 0.5)
    points(df$averages1_0_360 ~ unique(xdata), col='#f7f7f7', pch = 17, cex = 0.5)
    points(df$averages1.5_0_360 ~ unique(xdata), col='#cccccc', pch = 17, cex = 0.5)
    points(df$averages2_0_360 ~ unique(xdata), col='#969696', pch = 17, cex = 0.5)
    points(df$averages2.5_0_360 ~ unique(xdata), col='#636363', pch = 17, cex = 0.5)
    points(df$averages3_0_360 ~ unique(xdata), col='#252525', pch = 17, cex = 0.5)
    
    plot(df$averages1_1_60 ~ unique(xdata), col='#f7f7f7', xlab = xtext, 
         ylab = ytext, main = 'Sight = 1', ylim = c(0,ymax), pch = 19, cex = 0.5)
    points(df$averages1.5_1_60 ~ unique(xdata), col='#cccccc', pch = 19, cex = 0.5)
    points(df$averages2_1_60 ~ unique(xdata), col='#969696', pch = 19, cex = 0.5)
    points(df$averages2.5_1_60 ~ unique(xdata), col='#636363', pch = 19, cex = 0.5)
    points(df$averages3_1_60 ~ unique(xdata), col='#252525', pch = 19, cex = 0.5)
    points(df$averages1_1_360 ~ unique(xdata), col='#f7f7f7', pch = 17, cex = 0.5)
    points(df$averages1.5_1_360 ~ unique(xdata), col='#cccccc', pch = 17, cex = 0.5)
    points(df$averages2_1_360 ~ unique(xdata), col='#969696', pch = 17, cex = 0.5)
    points(df$averages2.5_1_360 ~ unique(xdata), col='#636363', pch = 17, cex = 0.5)
    points(df$averages3_1_360 ~ unique(xdata), col='#252525', pch = 17, cex = 0.5)
    
    plot(df$averages1_2_60 ~ unique(xdata), col='#f7f7f7', xlab = xtext, 
         ylab = ytext, main = 'Sight = 2', ylim = c(0,ymax), pch = 19, cex = 0.5)
    points(df$averages1.5_2_60 ~ unique(xdata), col='#cccccc', pch = 19, cex = 0.5)
    points(df$averages2_2_60 ~ unique(xdata), col='#969696', pch = 19, cex = 0.5)
    points(df$averages2.5_2_60 ~ unique(xdata), col='#636363', pch = 19, cex = 0.5)
    points(df$averages3_2_60 ~ unique(xdata), col='#252525', pch = 19, cex = 0.5)
    points(df$averages1_2_360 ~ unique(xdata), col='#f7f7f7', pch = 17, cex = 0.5)
    points(df$averages1.5_2_360 ~ unique(xdata), col='#cccccc', pch = 17, cex = 0.5)
    points(df$averages2_2_360 ~ unique(xdata), col='#969696', pch = 17, cex = 0.5)
    points(df$averages2.5_2_360 ~ unique(xdata), col='#636363', pch = 17, cex = 0.5)
    points(df$averages3_2_360 ~ unique(xdata), col='#252525', pch = 17, cex = 0.5)
    
    plot(df$averages1_5_60 ~ unique(xdata), col='#f7f7f7', xlab = xtext, 
         ylab = ytext, main = 'Sight = 5', ylim = c(0,ymax), pch = 19, cex = 0.5)
    points(df$averages1.5_5_60 ~ unique(xdata), col='#cccccc', pch = 19, cex = 0.5)
    points(df$averages2_5_60 ~ unique(xdata), col='#969696', pch = 19, cex = 0.5)
    points(df$averages2.5_5_60 ~ unique(xdata), col='#636363', pch = 19, cex = 0.5)
    points(df$averages3_5_60 ~ unique(xdata), col='#252525', pch = 19, cex = 0.5)
    points(df$averages1_5_360 ~ unique(xdata), col='#f7f7f7', pch = 17, cex = 0.5)
    points(df$averages1.5_5_360 ~ unique(xdata), col='#cccccc', pch = 17, cex = 0.5)
    points(df$averages2_5_360 ~ unique(xdata), col='#969696', pch = 17, cex = 0.5)
    points(df$averages2.5_5_360 ~ unique(xdata), col='#636363', pch = 17, cex = 0.5)
    points(df$averages3_5_360 ~ unique(xdata), col='#252525', pch = 17, cex = 0.5)
    
    plot(df$averages1_10_60 ~ unique(xdata), col='#f7f7f7', xlab = xtext, 
         ylab = ytext, main = 'Sight = 10', ylim = c(0,ymax), pch = 19, cex = 0.5)
    points(df$averages1.5_10_60 ~ unique(xdata), col='#cccccc', pch = 19, cex = 0.5)
    points(df$averages2_10_60 ~ unique(xdata), col='#969696', pch = 19, cex = 0.5)
    points(df$averages2.5_10_60 ~ unique(xdata), col='#636363', pch = 19, cex = 0.5)
    points(df$averages3_10_60 ~ unique(xdata), col='#252525', pch = 19, cex = 0.5)
    points(df$averages1_10_360 ~ unique(xdata), col='#f7f7f7', pch = 17, cex = 0.5)
    points(df$averages1.5_10_360 ~ unique(xdata), col='#cccccc', pch = 17, cex = 0.5)
    points(df$averages2_10_360 ~ unique(xdata), col='#969696', pch = 17, cex = 0.5)
    points(df$averages2.5_10_360 ~ unique(xdata), col='#636363', pch = 17, cex = 0.5)
    points(df$averages3_10_360 ~ unique(xdata), col='#252525', pch = 17, cex = 0.5)
    
    plot(df$averages1_20_60 ~ unique(xdata), col='#f7f7f7', xlab = xtext, 
         ylab = ytext, main = 'Sight = 20', ylim = c(0,ymax), pch = 19, cex = 0.5)
    points(df$averages1.5_20_60 ~ unique(xdata), col='#cccccc', pch = 19, cex = 0.5)
    points(df$averages2_20_60 ~ unique(xdata), col='#969696', pch = 19, cex = 0.5)
    points(df$averages2.5_20_60 ~ unique(xdata), col='#636363', pch = 19, cex = 0.5)
    points(df$averages3_20_60 ~ unique(xdata), col='#252525', pch = 19, cex = 0.5)
    points(df$averages1_20_360 ~ unique(xdata), col='#f7f7f7', pch = 17, cex = 0.5)
    points(df$averages1.5_20_360 ~ unique(xdata), col='#cccccc', pch = 17, cex = 0.5)
    points(df$averages2_20_360 ~ unique(xdata), col='#969696', pch = 17, cex = 0.5)
    points(df$averages2.5_20_360 ~ unique(xdata), col='#636363', pch = 17, cex = 0.5)
    points(df$averages3_20_360 ~ unique(xdata), col='#252525', pch = 17, cex = 0.5)
    
  }
  
}